In [2]:
import numpy as np
from scipy.spatial.transform import Rotation as R

In [4]:
camR2camL = [0.3987197408845486, -0.001707223726285425, 0.0068598299240638805, 0.000996027573104912, -0.006515031817384763, -0.0018497486047728876, 0.9999765700853152]

In [5]:
translation = camR2camL[:3]
quaternion = camR2camL[3:]

In [6]:
rot = R(quaternion)
transform = np.identity(4)
transform[:3, :3] = rot.as_matrix()
transform[:3, 3] = translation

In [7]:
camR2camL = transform

In [8]:
lidar2camL = np.array([[0.01498316835973168, -0.999874136398744, -0.0052168981943206405, 0.23],
                       [-0.005902540726116401, 0.005128945481573888, -0.9999694264982424, -0.1],
                        [0.999870323931499, 0.015013503225863423, -0.005824949957425718, -0.05],
                        [0.0, 0.0, 0.0, 1.0]])

In [9]:
camR2imu = np.array([[0.01573309, -0.99986094, 0.00552923, 0.01750096],
                     [0.00562882, -0.00544126, -0.99996935, -0.02215593],
                     [0.99986038,  0.01576373,  0.00554243, -0.07330212],
                     [0.        ,  0.        ,  0.        ,  1.        ]])

In [10]:
lidar2imu = lidar2camL @ np.linalg.inv(camR2camL) @ camR2imu

In [12]:
lidar2imu

array([[-0.01248568, -0.0060324 ,  0.99990385,  0.24667889],
       [-0.99965693, -0.02295062, -0.01262105, -0.02271339],
       [ 0.02302455, -0.9997184 , -0.00574377, -0.43199534],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [13]:
rot = R.from_matrix(lidar2imu[:3, :3])
quaternion_lidar2imu = rot.as_quat()
translation_lidar2imu = lidar2imu[:3, 3]

In [14]:
quaternion_lidar2imu

array([ 0.50403589, -0.49881831,  0.50736883, -0.48959675])

In [15]:
translation_lidar2imu

array([ 0.24667889, -0.02271339, -0.43199534])